services:
  - type: cron
    name: rfp-crawler
    runtime: docker
    dockerfilePath: ./Dockerfile
    schedule: "0 2 * * *"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    disk:
      name: rfp-data
      mountPath: /app/shared
      sizeGB: 1

  - type: web
    name: rfp-dashboard
    runtime: python
    buildCommand: "pip install -r dashboard/requirements.txt"
    startCommand: "streamlit run dashboard/app.py --server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
    disk:
      name: rfp-data
      mountPath: /opt/render/project/src/shared
      sizeGB: 1
