services:
  - type: cron
    name: rfp-crawler
    runtime: python
    buildCommand: "apt-get update -qq && apt-get install -y chromium-browser && pip install -r crawler/requirements.txt"
    startCommand: "bash crawler/start.sh"
    schedule: "0 2 * * *"
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false

  - type: web
    name: rfp-dashboard
    runtime: python
    buildCommand: "pip install -r dashboard/requirements.txt"
    startCommand: "streamlit run dashboard/app.py --server.port=$PORT"
