services:
  - type: web
    name: rfp-dashboard
    env: python
    buildCommand: pip install -r dashboard/requirements.txt
    startCommand: cd dashboard && streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16

  - type: worker
    name: rfp-crawler
    env: python
    buildCommand: |
      pip install -r crawler/requirements.txt
      playwright install chromium
    startCommand: cd crawler && bash start.sh
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.16
