services:
  - type: web
    name: rfp-dashboard
    env: python
    buildCommand: pip install -r dashboard/requirements.txt
    startCommand: cd dashboard && streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16

  - type: worker
    name: rfp-crawler
    env: python
    buildCommand: |
      pip install -r crawler/requirements.txt
      playwright install --with-deps chromium
    startCommand: |
      cd crawler
      playwright install chromium
      python main.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.16

  - type: cron
    name: rfp-crawler-scheduled
    env: python
    buildCommand: |
      pip install -r crawler/requirements.txt
      playwright install --with-deps chromium
    startCommand: |
      cd crawler
      playwright install chromium
      python main.py
    schedule: "0 2 * * *"  # Daily at 2 AM UTC
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.16
