# render.yaml - MVP Deployment Configuration

services:
  # Backend Cron Job - Runs the RFP crawler
  - type: cron
    name: rfp-crawler-mvp
    runtime: python
    buildCommand: |
      echo "Installing Python dependencies..."
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "Installing Playwright browsers..."
      playwright install chromium
      echo "Creating shared directory..."
      mkdir -p /opt/render/project/src/shared
      echo "Build completed successfully!"
    startCommand: python main_crawler.py
    schedule: "0 9 * * MON,WED,FRI"  # Run Mon, Wed, Fri at 9 AM UTC (5 AM EST)
    
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false  # You'll set this manually in Render dashboard
      - key: SCHOOL_DISTRICTS
        value: "https://www.boone.kyschools.us,https://www.carroll.kyschools.us"
      - key: CRAWLER_MAX_PAGES
        value: "15"
      - key: CRAWLER_MAX_DEPTH
        value: "2"
      - key: CRAWL_DELAY
        value: "2"
      - key: SHARED_DIR
        value: "/opt/render/project/src/shared"
      - key: LOG_LEVEL
        value: "INFO"
    
  # Frontend Web Service - Dashboard
  - type: web
    name: rfp-dashboard-mvp
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r frontend_requirements.txt
    startCommand: python dashboard/app.py
    
    envVars:
      - key: SHARED_DIR
        value: "/opt/render/project/src/shared"
      - key: FLASK_ENV
        value: "production"